---
title: INK Style Library
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  visual_identity:
    title: Visual Identity
    output: true
    display: true
    order: "1"
  messaging:
    title: Messaging
    output: true
    display: true
    order: "2"
  audience:
    title: Audience
    output: true
    display: true
    order: "3"
  writing_guide:
    title: Writing Guide
    output: true
    display: true
    order: "4"
  resources:
    title: Resources
    output: true
    display: true
    order: "5"
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: default
- scope:
    path: ''
    type: messaging
  values:
    layout: collection
- scope:
    path: ''
    type: visual_identity
  values:
    layout: collection
- scope:
    path: ''
    type: audience
  values:
    layout: collection
- scope:
    path: ''
    type: writing_guide
  values:
    layout: collection
- scope:
    path: ''
    type: resources
  values:
    layout: collection
- scope:
    path: "assets/illustrations/scene"
  values:
    type: 'scene'
- scope:
    path: "assets/illustrations/spot"
  values:
    type: 'spot'
- scope:
    path: "assets/photography/headshots"
  values:
    type: 'headshot'
- scope:
    path: "assets/photography/workplace"
  values:
    type: 'workplace'
email: stephen@ink-co.com
description: Library of INK brand assets for easy access and application.
baseurl: ''
url: ''
twitter_username: heyINKco
github_username: stephenbarkan
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
- jekyll-autoprefixer
